#.github/workflows/github.yml
name: AWS CloudFormation Deployment

on:
    push:
    pull_request:
        types:
            - opened
            - synchronize
            - closed

    workflow_dispatch:
        inputs:
            cloudformation-deploy:
                description: "Deploy the stack"
                type: boolean
                default: false

            aws-region:
                description: "AWS Region"
                default: ap-south-1

            template-file:
                description: "CloudFormation template file"
                default: MainStack.yml

permissions:
    id-token: write
    contents: read

jobs:
    cloudformation-deploy:
        uses: prabhashbhajnai/ci-template/.github/workflows/cloudformation-deploy.yml@main
        with:
            aws-region: ${{ inputs.aws-region }}
            template-file: ${{ inputs.template-file }}
            cloudformation-deploy: ${{ inputs.cloudformation-deploy || false }}
        secrets: inherit
